### ISSUE TITLE
[BUG/ISSUE] cannot generate world

### ISSUE THREAD

**Issue by Jolteon1234amongus** [CERBON-MODS/CERBONs-API#1]
Minecraft 1.20.1
Forge 47.2.0
CerbonsAPI-Forge-1.20.1-1.1.0.jar

Latest Log:
https://mclo.gs/oUsekxz

Describe the bug:
Cannot generate world

Go to singleplayer
Generate a new world on creative/hard/cheats on

Expected behavior:
It to generate world without error

![image](https://github.com/CERBON-MODS/CERBONs-API/assets/100394766/bab0140c-f0aa-4c1c-acd0-f8c141020a80)

**Comment by CerbonXD** [comment]
Install Bosses of Mass Desfrucion(BOMD) 1.1.2 version and it should work.
